target = "_sampledir"
topdir = "_sampledir"
tables = "tbl.txt"
template = "tmpl.md"
db = "%s:%s@/%s?charset=utf8&parseTime=True&loc=Local"

[filter]
out = ["vendor",".*test.*","ddl"]
in = ["in_dir",".*\\.go",".*\\.toml",".*\\.php",".*\\.rb",".*\\.py"]
